### ISSUE TITLE
FTP deployer: Cannot deploy to arbitrary directory

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#10]
I have this line in the "Artifacts path:" text field:

*-api*/target/*.jar=>/tmp

FTP deployer does not (as I would expect) try to deploy to /tmp on the target server
but rather to /home/deployuser/tmp

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/10
- Originally reported by: Christian Schmitt
- Originally created at: 2013-02-26T12:20:43.996

**Comment by nskvortsov** [comment]
Christian,

Unfortunately, TeamCity doesn't allow to specify absolute targets in "Artifacts path:" as this field is designed to contain relative destinations.
To deploy to absolute paths via FTP, add "/" to the value of "Target" field, e.g. (for "/tmp"):

Target: 192.168.0.1:21/
Artifact paths: -api/target/*.jar=>tmp

Also, I made a fix to suppot absolute roots, so please, update the plugin from [this build](http://teamcity.jetbrains.com/viewLog.html?buildId=78311&tab=buildResultsDiv&buildTypeId=bt402&guest=1)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
fixed in [this build](http://teamcity.jetbrains.com/viewLog.html?buildId=78311&tab=buildResultsDiv&buildTypeId=bt402&guest=1)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Great. Works with absolute paths as well.
BTW, did you change the code in a way that now the whole directory structure is copied and not only the jar file? I believe it was different before.

----------------------------------------
Original comment by: Christian Schmitt

**Comment by nskvortsov** [comment]
Christian, sorry for the delay.

What is exactly the problem with directory structure?

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Hmmm, I can't try and reproduce at the moment, but I believe the problem was like this:

I.e. you set /tmp as the target directory, I would have expected that the matching jar files are deployed to 
/tmp/myjar1.jar 
/tmp/mysecond.jar 
and so on.

As far as I can remember from February, the FTP deployer took the source directory structure into account and deployed the jars to something like:
/tmp/my/dir/structure/myjar1.jar 
/tmp/my/dir/structure/mysecond.jar 

I'm sorry that I can't be of more help at the moment.

Regards,
Christian


----------------------------------------
Original comment by: Christian Schmitt

**Comment by nskvortsov** [comment]
I see. Artifacts paths are processed using internal TeamCity component, I do not think something has changed. Just let me know if you have any problems with this, maybe open a separate issue.

Also, I will be re-implementing the fix for the issue with absolute paths, so that plugin better follows the RFC 1738. In the next version, one will have to specify leading slash as a %2F encoded symbol.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by morawi-cg** [comment]
Hi Nikita, I'm new to teamcity so would appreciate your help and patience. need to copy a file from my repo  
        teamcity/mongodb-org-4.0.repo
      to a team city (target for deployment server), the target ip was used 172.19.246.249:/etc/yum.repos.d/  I'm using ssh upload, could you kindly provide me with the syntax!

**Comment by nskvortsov** [comment]
Hi @morawi-cg , 
Before reading further, please, take a look at [basic concepts page](https://confluence.jetbrains.com/display/TCD18/Continuous+Integration+with+TeamCity) of TeamCity documentation.
To use deploy runner, you need to set up a build configuration:
* checks out sources from version control (Git url)
* runs a single build step `SSH Deploy` that has `172.19.246.249` as target server, proper username/password and `/etc/yum.repos.d/` as target directory.
If you want to upload all content of the repo there, you can use `**=>.` artifact path pattern
