### ISSUE TITLE
FTP password field should note that it accepts parameters.

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#15]
While the FTP Username field states that it accepts parameters, the Password field does not.  Through trying it, I discovered that putting a parameter in that field works (i.e., the password used is the one prompted for in the Run dialog), but it would be nice if that were noted in the documentation.

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/15
- Originally reported by: Anonymous
- Originally created at: 2013-06-14T19:00:16.474

**Comment by nskvortsov** [comment]
Thank you, this is indeed by design. I have added a note.
Fixed in [this build](teamcity.jetbrains.com/viewLog.html?buildId=87530)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by jakubp** [comment]
I think the same may apply to SSH Exec and SSH Deployer jobs - I pick Authentication Method: Password. Username has parameter hints, but password field does not. Still, after pasting %param_name% into ****** password field it seems to pick the value from the password parameter just fine.
